_target_: pytorch_lightning.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 10

accelerator: ddp
gpus: 2
devices: [0, 1]

#strategy: ddp_spawn
#num_nodes: 1
#sync_batchnorm: True

# mixed precision for extra speed-up
# precision: 16

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
