_target_: src.models.motionencoder.dalle_mask_image_embedding.DalleMaskImageEmbedding

# diffusion_step: 100

num_embed: 2048 #or 2047?
# spatial_size: [32, 32]
embed_dim: 64
trainable: true
pos_emb_type: embedding