_target_: src.models.motionencoder.diffusion_transformer.DiffusionTransformer

diffusion_step: 50
alpha_init_type: 'alpha1'       # init_type = fix or cos or linear 
auxiliary_loss_weight: 5.0e-4
adaptive_auxiliary_loss: True
mask_weight: [1, 1]    # the loss weight on mask region and non-mask region
content_seq_len: 2048   # 2*16*16

learnable_cf: False
guidance_scale: 4

defaults:
  - /model/motionencoder/transformer_utils@transformer
