# _target_: src.models.text_motion_model.TextMotionModel
_target_: src.utils.evaluator.Evaluator
videoencoder:
  _target_: src.models.motionencoder.pytorch_i3d.InceptionI3d

checkpoint_paths: ${eval_ckpt}

# diversity_times: 30

# defaults:
#   - /model/textencoder/text_encoder_bi_gru_co@motionencoder.textencoder
#   - /model/motionencoder/motion_encoder_bi_gru_co@motionencoder.motion_encoder
#   - /model/motionencoder/conv_motion_snip_encoder@autoencoder.motionencoder
#   - /model/motiondecoder/conv_snip_motion_decoder@autoencoder.motiondecoder
