_target_: src.models.text_motion_model.TextMotionModel
generator:
  _target_: src.models.networks.tevet_diffusion.TevetDiffusion
  transforms: ${datamodule.transforms}
  checkpoint_path: /home/ICT2000/achemburkar/Downloads/kit_trans_enc_512/kit_trans_enc_512/model000400000.pt

losses:
  _target_: src.models.metrics.loss.ComputeLosses
  mode: smpl
  loss_dict:
    l_dummy: 1.0
  loss_opts:
    loss_feat_type: rfeats

latent_dim: 512
ff_size: 1024
num_layers: 8
num_head: 4
droupout: 0.1
activation: "gelu"
diffusion_steps: 1000

lr_args:
  gen_lr: 0

collate_fn: t2m_collate

do_evaluation: true

checkpoint_paths: # /home/ICT2000/achemburkar/Downloads/kit_trans_enc_512/kit_trans_enc_512/model000400000.pt

# have to change this hardcoded path
# checkpoint_path: /home/ICT2000/achemburkar/Desktop/TextMotionGenerator/logs/train/runs/2022-11-21_12-31-44/checkpoints/last.ckpt

defaults:
  - /model/textencoder/tevet_mlp@generator.textencoder
  - /model/motionencoder/tevet_transformer_encoder@generator.motionencoder

  - /model/evaluator@evaluator
