_target_: src.models.text_motion_model.TextMotionModel

generator:
  _target_: src.models.networks.videogpt_vq_vae.VQVAE
  checkpoint_path: /home/ICT2000/achemburkar/Downloads/t2mt/t2m/VQVAEV3_CB1024_CMT_H1024_NRES3/model/finest.tar
#  checkpoint_path: /home/ICT2000/achemburkar/Desktop/repos/TM2T/checkpoints/kit/VQVAEV3_CB1024_CMT_H1024_NRES3/model/finest.tar
  embedding_dim: 64
  n_codes: 2048
  n_hiddens: 240
  n_res_layers: 4
  downsample: [4, 4, 4]
  sequence_length: ${datamodule.sequence_length}
  resolution: ${datamodule.resolution}

losses:
  _target_: src.models.metrics.loss.ComputeLosses
  mode: smpl
  loss_dict:
    l_dummy: 1
  loss_opts:
    loss_feat_type: rfeats

lr_args:
  gen_lr: 1e-5

#checkpoint_paths: /home/ICT2000/achemburkar/Desktop/TextMotionGenerator/logs/train/runs/2023-03-08_13-44-20/checkpoints/last.ckpt

do_evaluation: false

collate_fn: ucf101_collate

devices: ${trainer.devices}

# defaults:
#   - /model/motionencoder/vq_encoder_v3_guo@generator.encoder
#   - /model/motiondecoder/vq_decoder_v3_guo@generator.decoder
#  - /model/motionencoder/vq_discriminator_guo@generator.discriminator
  # - /model/motionencoder/quantizer_guo@generator.quantizer
  # - /model/evaluator@evaluator
