_target_: src.models.motionencoder.resnet1d.Decoder

double_z: False
z_channels: 64
resolution: 64
in_channels: 135   # ${datamodule.motion_opt.pose_dim}
out_ch: 135    # ${datamodule.motion_opt.pose_dim}
ch: 64
ch_mult: [ 1,2,4]  # num_down = len(ch_mult)-1
num_res_blocks: 2
attn_resolutions: [ 16 ]
dropout: 0.0