dataname: humanml
_target_: src.datamodules.humanml_datamodule.HumanMLDataModule

# Paths
#datasets: /Desktop/repos/HumanML3D/HumanML3D/

# Andrew: here we should try to use the config files (i.e. paths/default.yaml) to unified the location changes on different machines.
# comment things for now.
#datapath: /home/ICT2000/achemburkar/Desktop/repos/HumanML3D/HumanML3D
#splitpath: /home/ICT2000/achemburkar/Desktop/repos/HumanML3D/HumanML3D

datapath: ${paths.datasets}/HumanML3D
splitpath: ${paths.datasets}/HumanML3D

# Amass
#load_amass_data: true
#load_with_rot: true
#correspondance_path: ${paths.datasets}/kit/kitml_amass_path.json
#amass_path: ${paths.datasets}/AMASS/SMPL+H
#smplh_path: ${paths.smpl_path}

# Text
#pick_one_text: true

# Machine
batch_size: ${batch_size}
num_workers: 0

# Motion
framerate: 20
joints_num: 22
dim_pose: 263
max_motion_length: 196
feat_bias: 20      # Guo Layers of GRU
defaults:
  - /datamodule/transforms/humanml_smpl.yaml@transforms
  - sampler: fix_conseq

# Other
tiny: false
progress_bar: true

# Collate_fn
collate_fn: ${model.collate_fn}

# Word_vectorizer etc.
deps: ${paths.deps}

devices: ${trainer.devices}
