dataname: msrvtt
_target_: src.datamodules.msrvtt_datamodule.MSRVTTDataModule

data_folder: ${paths.datasets}/MSRVTT
sequence_length: 4
resolution: 128
# splitpath: ${paths.datasets}/UCF101

# Machine
batch_size: ${batch_size}
num_workers: 0

# Other
tiny: false
progress_bar: true

# Collate_fn
collate_fn: msrvtt_collate

# Word_vectorizer etc.
# deps: ${paths.deps}

devices: ${trainer.devices}
