dataname: ufc101
_target_: src.datamodules.ucf101_datamodule.UCF101DataModule

data_folder: ${paths.datasets}/UCF101
sequence_length: 16
resolution: 128
# splitpath: ${paths.datasets}/UCF101

# Machine
batch_size: ${batch_size}
num_workers: 0

# Other
tiny: false
progress_bar: true

# Collate_fn
collate_fn: ${model.collate_fn}

# Word_vectorizer etc.
deps: ${paths.deps}

devices: ${trainer.devices}
